# Generated by Django 4.0.5 on 2022-06-07 14:18

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pronouns',
            field=models.CharField(default='they/them', max_length=32, verbose_name='Pronouns'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(default='', max_length=1024, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, verbose_name='Image'),
        ),
    ]
