# Generated by Django 4.0.5 on 2022-06-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_pronouns_alter_user_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_subscription',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Notification subscription'),
        ),
    ]
