# Generated by Django 4.0.5 on 2022-06-04 11:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(default='', max_length=1024, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('is_privacy_hidden', models.BooleanField(default=False, verbose_name='Privacy hidden')),
                ('join_mode', models.CharField(choices=[('PUB', 'Public'), ('URL', 'URL only'), ('INV', 'Invite only')], default='INV', max_length=3)),
                ('expected_time_per_ticket', models.FloatField(default=0, verbose_name='Expected time per ticket')),
                ('ticket_stats_count', models.IntegerField(default=0, verbose_name='Ticket status count')),
                ('fixed_ticket_time_seconds', models.IntegerField(default=None, null=True, verbose_name='Fixed ticket time (secs)')),
            ],
            options={
                'verbose_name': 'Queue',
                'verbose_name_plural': 'Queues',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('requested_time', models.DateTimeField(default=None, null=True, verbose_name='Requested time')),
                ('state', models.CharField(choices=[('OPE', 'Open'), ('UCA', 'Cancelled by the user'), ('QCA', 'Cancelled by a queue operator'), ('SER', 'Served')], default='OPE', max_length=3)),
                ('closure_time', models.DateTimeField(default=None, verbose_name='Closure time')),
                ('wait_time_secs', models.IntegerField(default=None, null=True, verbose_name='Wait time')),
                ('cancel_message', models.CharField(default=None, max_length=128, null=True, verbose_name='Closure message')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.qqueue', verbose_name='queue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='QueueUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWN', 'owner'), ('EMP', 'employee'), ('INV', 'invited')], default='OWN', max_length=3)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_set', to='queues.qqueue', verbose_name='queue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues_set', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='QueueOpenRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(7)], verbose_name='day')),
                ('from_time', models.TimeField(verbose_name='from')),
                ('to_time', models.TimeField(verbose_name='to')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='queues.qqueue', verbose_name='queue')),
            ],
            options={
                'verbose_name': 'Opening range',
                'verbose_name_plural': 'Opening ranges',
            },
        ),
        migrations.AddField(
            model_name='qqueue',
            name='tickets',
            field=models.ManyToManyField(related_name='tickets', through='queues.Ticket', to=settings.AUTH_USER_MODEL, verbose_name='tickets'),
        ),
        migrations.AddField(
            model_name='qqueue',
            name='users',
            field=models.ManyToManyField(related_name='queues', through='queues.QueueUser', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
