# Generated by Django 4.0.5 on 2022-06-04 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closure_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Closure time'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_set', to='queues.qqueue', verbose_name='queue'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_set', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
