# Generated by Django 4.0.5 on 2022-06-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_alter_ticket_closure_time_alter_ticket_queue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqueue',
            name='fixed_ticket_time_seconds',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Fixed ticket time (secs)'),
        ),
    ]
