# Generated by Django 4.0.5 on 2022-06-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_alter_qqueue_fixed_ticket_time_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qqueue',
            name='fixed_ticket_time_seconds',
        ),
        migrations.AddField(
            model_name='qqueue',
            name='fixed_ticket_time_minutes',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Fixed ticket time (minutes)'),
        ),
    ]
