# Generated by Django 4.0.5 on 2022-06-07 10:03

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0005_alter_ticket_requested_time_queueopenexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='qqueue',
            name='tz',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='Europe/Rome'),
        ),
    ]
