# Generated by Django 4.0.5 on 2022-06-30 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_remove_user_notification_subscription'),
        ('queues', '0007_alter_qqueue_join_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQueueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('reason', models.CharField(max_length=256, verbose_name='Reason')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Reviewed')),
            ],
        ),
        migrations.AddField(
            model_name='qqueue',
            name='reports',
            field=models.ManyToManyField(related_name='reported_queues', through='queues.UserQueueReport', to=settings.AUTH_USER_MODEL, verbose_name='reports'),
        ),
        migrations.AddField(
            model_name='userqueuereport',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_set', to='queues.qqueue', verbose_name='queue'),
        ),
        migrations.AddField(
            model_name='userqueuereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_reports_set', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
