# Generated by Django 4.0.5 on 2022-06-30 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0008_userqueuereport_qqueue_reports_userqueuereport_queue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userqueuereport',
            options={'permissions': [('manage_reports', 'Can view and review submitted reports'), ('view_all_stats', 'Can view stats of queues they do not own')]},
        ),
    ]
